apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostar-deployment
  labels:
    app: hostar
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hostar
  template:
    metadata:
      labels:
        app: hostar
    spec:
      containers:
      - name: my-container
        image: suraj143docker/hostar-image  # Replace with your image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hostar-service
spec:
  type: LoadBalancer
  selector:
    app: hostar
  ports:
    - port: 80
      targetPort: 80

